server:
  port: 8080

spring:
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
# 微信支付
wxpay:
  appId:
  mchId:
  mchKey:
  #  p12证书文件的绝对路径或者以classpath:开头的类路径.
  keyPath: classpath:wxpay_cert/apiclient_cert.p12
  #  apiclient_key.pem证书文件的绝对路径或者以classpath:开头的类路径.
  privateKeyPath: classpath:wxpay_cert/apiclient_key.pem
  privateCertPath: classpath:wxpay_cert/apiclient_cert.pem
  # 支付回调
  notifyUrl: https://4789j06630.wocp.fun/wechat/pay/notify
  # 退款回调
  refundNotifyUrl: https://4789j06630.wocp.fun/wechat/pay/refund_notify

# 支付宝支付
alipay:
  server_url: https://openapi.alipay.com/gateway.do
  app_id:
  private_key:
  format: json
  charset: utf-8
  alipay_public_key:
  sign_type: RSA2
  #  支付和退款回调都走这个
  notifyUrl: https://4789j06630.wocp.fun/alipay/notify

